id: PB3D8B1C3
initial_creation_type: ocr
source_metadata:
  volumes:
    24a574808c33488a8c3dec5e65ec45a4:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: ཐུགས་རྗེ་ཆེན་པོ་ལ་སྨྲེ་སྔགས་ཀྱིས་བསྟོད་པ་བྱིན་རླབས་ཅན།
      total_pages: 1379
      volume_number: 37
